<p style="text-align: justify; margin-top: 15px;">Berikut adalah beberapa ketentuan umum terkait dengan TKHT.</p>
<ol type="1" style="color: #555; font-size: .99rem">
    <li><p style="text-align: justify; margin-bottom: 6px;">Yayasan adalah Yayasan Kesejahteraan Karyawan Bank Indonesia.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Pengurus adalah Pengurus Yayasan yang terdiri dari Ketua, Sekretaris, dan Bendahara.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Pensiunan adalah karyawan Bank Indonesia yang berhenti bekerja dari Bank Indonesia sesuai dengan peraturan kepegawaian Bank Indonesia.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Keluarga adalah isteri dan/atau anak dari Pensiunan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Isteri adalah isteri yang sah dari Pensiunan yang ditanggung oleh Bank Indonesia pada saat yang bersangkutan berhenti dari jabatannya atau pensiun.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Anak adalah anak yang sah dari Pensiunan yang masih ditanggung oleh Bank Indonesia, pada saat yang bersangkutan berhenti dari jabatannya atau pensiun.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Tunjangan Kesehatan Hari Tua yang selanjutnya disebut TKHT adalah Tunjangan Hari Tua yang diberikan oleh Bank Indonesia kepada Pensiunan Bank Indonesia dan keluarganya dalam rangka pembiayaan pengobatan yang dikelola oleh Yayasan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Penerima TKHT adalah Pensiunan Bank Indonesia dan Keluarganya yang memenuhi persyaratan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Pejabat Negara adalah pimpinan dan / atau anggota lembaga negara sebagaimana dimaksud dalam Undang-Undang Dasar 1945 dan pejabat negara yang ditentukan Undang-Undang.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Pelayanan Kesehatan adalah pelayanan yang dilakukan dalam upaya pemulihan kesehatan dengan memperhatikan standar pelayanan kesehatan yang berlaku umum.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Wilayah Kesehatan adalah daerah tertentu yang ditetapkan Yayasan dalam rangka pembagian wilayah pelayanan kesehatan bagi Penerima TKHT yang di dalamnya terdapat Penyedia Pelayanan Kesehatan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Provider adalah Penyedia Pelayanan Kesehatan yang ditunjuk oleh Yayasan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Penyedia Pelayanan Kesehatan yang selanjutnya disebut PPK adalah dokter umum, dokter gigi umum, dokter spesialis/ sub spesialis, dokter gigi spesialis, laboratorium, radiologi, fisioterapi, apotek, klinik dan/atau rumah sakit.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Managed Care adalah suatu sistem pengelolaan kesehatan yang menggabungkan faktor pembiayaan dan pelayanan sehingga di dalamnya terdapat unsur kendali mutu dan kendali biaya.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Dokter Umum Langganan adalah dokter praktek umum yang terikat kerjasama dengan Yayasan untuk melaksanakan pelayanan kesehatan tingkat pertama secara menyeluruh dan berkesinambungan bagi Penerima TKHT dengan mengacu pada sistem dokter keluarga.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Rawat Jalan adalah konsultasi, pemeriksaan, dan pengobatan yang diberikan dalam upaya pemulihan kesehatan pasien yang tidak memerlukan rawat inap.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Rawat Inap adalah perawatan bagi pasien yang oleh karena keadaan kesehatannya memerlukan menginap di rumah sakit untuk dilakukan perawatan/pengobatan, dan atau tindakan medis.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Home Care adalah asuhan keperawatan pasien yang dilakukan di rumah sebagai kelanjutan dari perawatan di rumah sakit akibat sakit berat karena tidak ada perbaikan bermakna secara medis, dan tidak dapat dilakukan secara Rawat Jalan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Fasilitas Penunjang adalah fasilitas medis yang mendukung pelaksanaan Rawat Jalan atau Rawat Inap berupa laboratorium, apotek, radiodiagnostik, fisioterapi yang ditetapkan oleh Yayasan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Apotek Langganan adalah apotek yang ditunjuk Yayasan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Gawat Darurat adalah suatu kondisi kesehatan mendadak yang dapat berakibat fatal atau mengancam jiwa sehingga perlu penanganan medis secara cepat dan terpadu.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Ad Medika adalah anak perusahaan PT. Telkom Indonesia yang menjalankan otomasi administrasi TKHT menggunakan Sistem Teknologi Informasi kesehatan dengan nama e-healthcare YKKBI.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">Kartu e-healthcare YKKBI yang selanjutnya disebut Kartu Sehat TKHT adalah kartu magnetik yang diberikan kepada Penerima TKHT untuk digunakan sebagai kartu identitas kepesertaan bagi yang bersangkutan dalam rangka mendapat pelayanan TKHT menggunakan Sistem Teknologi Informasi kesehatan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">PPK Langganan online adalah PPK langganan YKKBI yang merupakan mitra kerja Ad Medika dalam rangka pelaksanaan TKHT menggunakan Sistem Teknologi Informasi kesehatan.</p></li>
    <li><p style="text-align: justify; margin-bottom: 6px;">PPK Langganan offline adalah PPK langganan YKKBI yang belum atau tidak menjadi mitra kerja Ad Medika sehingga tidak atau belum dapat melaksanakan TKHT menggunakan Sistem Teknologi Informasi kesehatan.</p></li>
</ol>